export type Region = {
	value: string,
	label: string
};
export const REGIONS: Region[] = [
	{ label:'Auvergne-Rhône-Alpes',
		value:'AURA' },
	{ label:'Bourgogne-Franche-Comté',
		value:'BOFC' },
	{ label:'Bretagne',
		value:'BRET' },
	{ label:'Centre-Val de Loire',
		value:'CVDL' },
	{ label:'Grand Est',
		value:'GEST' },
	{ label:'Guadeloupe',
		value:'GUA' },
	{ label:'Guyane',
		value:'GUY' },
	{ label:'Hauts-de-France',
		value:'HFRA' },
	{ label:'Ile-de-France',
		value:'LIFB' },
	{ label:'Martinique',
		value:'MAR' },
	{ label:'Nouvelle-Aquitaine',
		value:'NAQU' },
	{ label:'Nouvelle-Calédonie',
		value:'NCAL' },
	{ label:'Normandie',
		value:'NORM' },
	{ label:'Occitanie',
		value:'OCCI' },
	{ label:'La Réunion',
		value:'REU' },
	{ label:'Pays de la Loire',
		value:'PDLL' },
	{ label:'Provence-Alpes-Côte d’Azur',
		value:'PACA' },
];
